Update README.md
elisaado/somtoday-api-docs pull request #35
Opened 2024-06-19 09:48 UTC by MathijsBols

Added documentation for the icalander token.

2024-06-19 14:52 UTC, MattterSteege requested changes
Looking very nice, please look over the suggested changes to spelling and the addition of the `DELETE` request.

2024-06-19 14:52 UTC, MattterSteege commented on README.md
> +### ICalander: `GET /rest/v1/icalendar`
```suggestion
### ICalendar: `GET /rest/v1/icalendar`
```

2024-06-19 14:52 UTC, MattterSteege commented on README.md
> +Fetches the icalander token.
```suggestion
Fetches the url to the icalendar stream.
```

2024-06-19 14:52 UTC, MattterSteege commented on README.md
> +
```suggestion

### ICalendar: `DELETE /rest/v1/icalendar`
<details><summary>Click to open</summary>

Deletes the currently active icalendar stream

#### Parameters

| Name          | Type      | Value                 |
|---------------|-----------|-----------------------|
| Authorization | Header    | Bearer [access_token] |

#### Returns

NONE

</details>
```

2024-06-19 14:52 UTC, MattterSteege commented on README.md
> +    - [ICallander: `GET /rest/v1/icalendar`](#icalander-get-restv1icalendar)
```suggestion
    - [ICalendar: `GET /rest/v1/icalendar`](#icalendar-get-restv1icalendar)
    - [ICalendar: `DELETE /rest/v1/icalendar`](#icalendar-delete-restv1icalendar)
    ```

2024-06-21 09:53 UTC, MathijsBols commented
Is it done now?

2024-06-21 13:24 UTC, MattterSteege requested changes

2024-06-21 13:24 UTC, MattterSteege commented on README.md
> +    ```
```suggestion
```

2024-06-21 13:27 UTC, merged